<?php


namespace App;


class FontAwesomeIconGenerator
{
    static $icons = null;

    public static function getRandomIconClass()
    {
        if (is_null(self::$icons)) {
            self::initialize();
        }
        [$usec, $sec] = explode(' ', microtime());
        srand($sec + $usec * 1000000);

        return self::$icons[rand(0, count(self::$icons))];
    }

    private static function initialize()
    {
        self::$icons = [
            'fal fa-rows-alt-v',
            'fal fa-assistive-listening-systems',
            'fal fa-asterisk',
            'fal fa-at',
            'fal fa-atlas',
            'fal fa-atom',
            'fal fa-audio-description',
            'fal fa-award',
            'fal fa-baby',
            'fal fa-baby-carriage',
            'fal fa-backspace',
            'fal fa-backward',
            'fal fa-bacon',
            'fal fa-bacteria',
            'fal fa-bacterium',
            'fal fa-bahai',
            'fal fa-balance-scale',
            'fal fa-balance-scale-left',
            'fal fa-balance-scale-right',
            'fal fa-ban',
            'fal fa-band-aid',
            'fal fa-barcode',
            'fal fa-bars',
            'fal fa-baseball-ball',
            'fal fa-basketball-ball',
            'fal fa-bath',
            'fal fa-battery-empty',
            'fal fa-battery-full',
            'fal fa-battery-half',
            'fal fa-battery-quarter',
            'fal fa-battery-three-quarters',
            'fal fa-bed',
            'fal fa-beer',
            'fal fa-bell',
            'fal fa-bell-slash',
            'fal fa-bezier-curve',
            'fal fa-bible',
            'fal fa-bicycle',
            'fal fa-biking',
            'fal fa-binoculars',
            'fal fa-biohazard',
            'fal fa-birthday-cake',
            'fal fa-blender',
            'fal fa-blender-phone',
            'fal fa-blind',
            'fal fa-blog',
            'fal fa-bold',
            'fal fa-bolt',
            'fal fa-bomb',
            'fal fa-bone',
            'fal fa-bong',
            'fal fa-book',
            'fal fa-book-dead',
            'fal fa-book-medical',
            'fal fa-book-open',
            'fal fa-book-reader',
            'fal fa-bookmark',
            'fal fa-border-all',
            'fal fa-order-none',
            'fal fa-border-style',
            'fal fa-bowling-ball',
            'fal fa-box',
            'fal fa-box-open',
            'fal fa-box-tissue',
            'fal fa-boxes',
            'fal fa-braille',
            'fal fa-brain',
            'fal fa-bread-slice',
            'fal fa-briefcase',
            'fal fa-briefcase-medical',
            'fal fa-broadcast-tower',
            'fal fa-broom',
            'fal fa-brush',
            'fal fa-bug',
            'fal fa-building',
            'fal fa-bullhorn',
            'fal fa-bullseye',
            'fal fa-burn',
            'fal fa-bus',
            'fal fa-bus-alt',
            'fal fa-business-time',
            'fal fa-calculator',
            'fal fa-calendar',
            'fal fa-calendar-alt',
            'fal fa-calendar-check',
            'fal fa-calendar-day',
            'fal fa-calendar-minus',
            'fal fa-calendar-plus',
            'fal fa-calendar-times',
            'fal fa-calendar-week',
            'fal fa-camera',
            'fal fa-camera-retro',
            'fal fa-campground',
            'fal fa-candy-cane',
            'fal fa-cannabis',
            'fal fa-capsules',
            'fal fa-car',
            'fal fa-car-alt',
            'fal fa-car-battery',
            'fal fa-car-crash',
            'fal fa-car-side',
            'fal fa-caravan',
            'fal fa-caret-down',
            'fal fa-caret-left',
            'fal fa-caret-right',
            'fal fa-caret-square-down',
            'fal fa-caret-square-left',
            'fal fa-caret-square-right',
            'fal fa-caret-square-up',
            'fal fa-caret-up',
            'fal fa-carrot',
            'fal fa-cart-arrow-down',
            'fal fa-cart-plus',
            'fal fa-cash-register',
            'fal fa-cat',
            'fal fa-certificate',
            'fal fa-chair',
            'fal fa-chalkboard',
            'fal fa-chalkboard-teacher',
            'fal fa-charging-station',
            'fal fa-chart-area',
            'fal fa-chart-bar',
            'fal fa-chart-line',
            'fal fa-chart-pie',
            'fal fa-check',
            'fal fa-check-circle',
            'fal fa-check-double',
            'fal fa-check-square',
            'fal fa-cheese',
            'fal fa-chess',
            'fal fa-chess-bishop',
            'fal fa-chess-board',
            'fal fa-chess-king',
            'fal fa-chess-knight',
            'fal fa-chess-pawn',
            'fal fa-chess-queen',
            'fal fa-chess-rook',
            'fal fa-chevron-circle-down',
            'fal fa-chevron-circle-left',
            'fal fa-chevron-circle-right',
        ];
    }

}
